package week2.Threads;

public class Resulttask extends Thread {
	public void run() {
		System.out.println("Result generated by :" + Thread.currentThread().getName());
	}
	
	public static void main(String[] args) {
		Resulttask t1=new Resulttask();
		t1.run(); //Normal execution
		t1.start();//start() is ffor multitasking and multithreading.
		//start() internally calls run()
		//Thread cannot be started twice
		
	}

}
